variant: fcos
version: 1.6.0

passwd:
  users:
    - name: core
      should_exist: false
    - name: nick
      uid: 1000
      groups: [wheel]
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEjRfPMkXzhO4unF0mEOHge+wGAE9VarXYo7RRXX2L3j
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBgtZmKuTJY2z88tCrtexFTPmXGA6oR1m4XQVn8ZLzmj

storage:
  files:
    - path: /etc/sudoers.d/nick
      mode: 0440
      contents:
        inline: |
          nick ALL=(ALL) NOPASSWD:ALL
    - path: /etc/motd
      mode: 0644
      contents:
        inline: |
          Welcome Nick! Please don't forget to set a passwd using:
          sudo passwd nick

systemd:
  units:
    - name: getty@tty1.service
      enabled: true
      dropins:
        - name: override.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=-/sbin/agetty --autologin nick --noclear %I $TERM

    - name: sshd.service
      enabled: true

    - name: zincati.service
      enabled: true

    - name: podman.socket
      enabled: true

    - name: set-timezone.service
      enabled: true
      contents: |
        [Unit]
        Description=Set timezone to Europe/Amsterdam
        After=network.target

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/timedatectl set-timezone Europe/Amsterdam

        [Install]
        WantedBy=multi-user.target
